name: Refresh News Articles

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours UTC
  workflow_dispatch:        # Allow manual runs

jobs:
  refresh-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" > .env

    - name: Run refresh pipeline
      run: |
        python src/pipeline/refresh_pipeline.py

    - name: Upload files to EC2 via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "data/processed/articles_faiss.index,data/processed/article_metadata.json"
        target: ${{ secrets.EC2_TARGET_PATH }}
